version: '2'

volumes:
  pg:

services:
  app:
    restart: always
    image: tippenein/dusk
    env_file:
      - app.env
    ports:
      - "80:8081"
    depends_on:
      - db

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_USER     = dusk
      - POSTGRES_PASSWORD = dusk
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - "5432:5432"
