name: rsvp-site
version: '0.0.0'
license: UnspecifiedLicense
default-extensions:
- BangPatterns
- ConstraintKinds
- DataKinds
- DeriveDataTypeable
- DeriveGeneric
- EmptyDataDecls
- FlexibleContexts
- FlexibleInstances
- GADTs
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- NoImplicitPrelude
- NoMonomorphismRestriction
- OverloadedStrings
- QuasiQuotes
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- TemplateHaskell
- TupleSections
- TypeFamilies
- TypeOperators
- ViewPatterns
library:
  source-dirs: src
  exposed-modules:
  - Application
  - Routes
  - AppType
  - Foundation
  - Helpers.Util
  - SendMail
  - Helpers.Forms
  - Helpers.Presentation
  - Api.V3.MailGun
  - Import
  - Import.NoFoundation
  - Model
  - Model.BCrypt
  - Model.Instances
  - Settings
  - Settings.StaticFiles
  - S3
  - Handler.Common
  - Handler.Home
  - Handler.Profile
  - Handler.Admin.Event
  - Handler.Admin.Curator
  - Handler.Curator
  - Handler.Event
  dependencies:
  - base >=4.8.2.0 && <4.9 || >=4.9.1.0 && <5
  - yesod >=1.4.3 && <1.5
  - yesod-core >=1.4.30 && <1.5
  - yesod-auth >=1.4.0 && <1.5
  - yesod-static >=1.4.0.3 && <1.6
  - yesod-form >=1.4.0 && <1.5
  - classy-prelude >=0.10.2
  - classy-prelude-conduit >=0.10.2
  - classy-prelude-yesod >=1.1
  - bytestring >=0.9 && <0.11
  - text >=0.11 && <2.0
  - persistent >=2.0 && <2.7
  - persistent-postgresql >=2.1.1 && <2.7
  - persistent-template >=2.0 && <2.7
  - esqueleto
  - template-haskell
  - shakespeare >=2.0 && <2.1
  - hjsmin >=0.1 && <0.3
  - monad-control >=0.3 && <1.1
  - wai-extra >=3.0 && <3.1
  - yaml >=0.8 && <0.9
  - http-conduit >=2.1 && <2.3
  - directory >=1.1 && <1.4
  - warp >=3.0 && <3.3
  - data-default
  - aeson >=0.6 && <1.1
  - conduit >=1.0 && <2.0
  - conduit-extra >=1.0 && <2.0
  - monad-logger >=0.3 && <0.4
  - fast-logger >=2.2 && <2.5
  - wai-logger >=2.2 && <2.4
  - resourcet
  - file-embed
  - bcrypt
  - safe
  - errors
  - unordered-containers
  - containers
  - vector
  - time
  - amazonka
  - amazonka-s3
  - amazonka-core
  - transformers
  - elm-export
  - elm-export-persistent
  - lens
  - uuid
  - mime-mail
  - http-client
  - case-insensitive
  - wai
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
      dependencies:
      - foreign-store
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2
executables:
  rsvp-site:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - rsvp-site
    when:
    - condition: flag(library-only)
      buildable: false

  seed:
    main:           Seed.hs
    source-dirs:    test
    dependencies:
    - base
    - time
    - rsvp-site
    - monad-logger
    - persistent
    - persistent-postgresql
  gen:
    main: Main.hs
    source-dirs:    gen
    dependencies:
    - base
    - rsvp-site
    - elm-export
    - uuid
    - persistent
    - bytestring
    - classy-prelude-yesod
    - text
    - bcrypt
    - safe
    - esqueleto
    - elm-export-persistent

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - base
    - rsvp-site
    - yesod-auth
    - yesod-test >=1.5.2 && <1.6
    - yesod-core
    - yesod
    - persistent
    - persistent-postgresql
    - resourcet
    - monad-logger
    - shakespeare
    - transformers
    - hspec >=2.0.0
    - classy-prelude
    - classy-prelude-yesod
    - aeson
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
